/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/01ChBwINbXI
 */
import md5 from 'md5';
import {CardDescription, CardTitle, CardHeader, CardContent, Card} from "@/components/ui/card";

export function MainScreen() {
    // Function to generate a random email for an employee
    const generateRandomEmail = () => {
        const randomString = Math.random().toString(36).substring(2, 8);
        return `${randomString}@rtu.edu`;
    };

    // Function to get Gravatar URL based on email
    const getGravatarUrl = (email: string) => {
        const hash = md5(email.toLowerCase());
        return `https://www.gravatar.com/avatar/${hash}?s=100&d=wavatar`;
    };

    // Example data for employees
    const employees = [
        {name: 'Jane Doe', role: 'Teacher'},
        {name: 'John Doe', role: 'Teacher'},
        {name: 'Emily Smith', role: 'Teacher'},
        {name: 'Robert Johnson', role: 'Teacher'},
        {name: 'Mary Brown', role: 'Teacher'},
        {name: 'Paul Davis', role: 'Teacher'},
        {name: 'Linda Jackson', role: 'Teacher'},
    ];

    return (
        <div className="flex flex-col w-screen h-screen">
            <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6 overflow-x-auto">
                <div className="flex items-center gap-4">
                    <h1 className="font-semibold text-lg md:text-xl">RTU Employee Presence</h1>
                </div>
                <div className="grid md:grid-cols-3 gap-6">
                    {employees.map((employee, index) => (
                        <Card key={index} className="flex flex-col w-3/4">
                            <CardHeader className="flex items-center gap-4">
                                <img
                                    alt="Employee Image"
                                    className="rounded-full"
                                    height="36"
                                    src={getGravatarUrl(generateRandomEmail())}
                                    style={{
                                        aspectRatio: "36/36",
                                        objectFit: "cover",
                                    }}
                                    width="36"
                                />
                                <div>
                                    <CardDescription>{employee.role}</CardDescription>
                                    <CardTitle>{employee.name}</CardTitle>
                                </div>
                            </CardHeader>
                            <CardContent>
                                <div className="grid gap-4">
                                    <div className="flex items-center">
                                        <div>Status</div>
                                        <div className="ml-auto">
                                            <CheckCircleIcon className="h-5 w-5 text-green-500"/>
                                        </div>
                                    </div>
                                    <div className="flex items-center">
                                        <div>Last Checked</div>
                                        <div className="ml-auto font-semibold">10:{index * 5 + 30} AM</div>
                                    </div>
                                </div>
                            </CardContent>
                        </Card>
                    ))}
                </div>
                <div className="flex justify-center items-center gap-3 mt-3">
                    <div className="w-2 h-2 bg-gray-400 rounded-full"/>
                    <div className="w-2 h-2 bg-gray-400 rounded-full"/>
                    <div className="w-2 h-2 bg-gray-400 rounded-full"/>
                    <div className="w-2 h-2 bg-gray-400 rounded-full"/>
                    <div className="w-2 h-2 bg-gray-400 rounded-full"/>
                    <div className="w-2 h-2 bg-gray-400 rounded-full"/>
                    <div className="w-2 h-2 bg-gray-400 rounded-full"/>
                </div>
            </main>
        </div>
    );
}

// define props type here
export interface CheckCircleIconProps {
    className?: string;
    style?: React.CSSProperties;
}

function CheckCircleIcon(props: CheckCircleIconProps) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/>
            <polyline points="22 4 12 14.01 9 11.01"/>
        </svg>
    );
}